/* NEON FORGE — ESLint flat config.
   The app itself ships with zero runtime dependencies, but static checks
   keep the modular source honest: no unused vars, no undefined globals,
   browser + node environments (tests/tools run in node, ui in browser). */
import js from "@eslint/js";
import globals from "globals";

export default [
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "Tetech-main/**",     /* legacy source of the verbatim data — read-only */
      "tools/legacy/**",    /* kept for reference, not maintained */
      "ui/version.js"       /* generated by tools/stamp.js */
    ]
  },
  js.configs.recommended,
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.browser, ...globals.node }
    },
    rules: {
      "no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-constant-condition": ["error", { checkLoops: false }]
    }
  }
];
